### ISSUE TITLE
请问这个库对已经上传iCloud的照片， 展示的逻辑是怎样的？

### ISSUE THREAD

**Issue by GodzzZZZ** [cbangchen/CBPic2ker#3]
这个库很棒， 想咨询上传iCloud的照片， 展示的逻辑。

**Comment by GodzzZZZ** [comment]
看了处理逻辑， 好像是不支持gif？

**Comment by cbangchen** [comment]
建议不要使用这个库。不打算更新了，近期会对本库进行删除。确实不支持 GIF，iCloud的逻辑也没有考虑。有很多不足之处。见谅。
